language: python
os:
    - linux
dist: bionic
python:
    - 3.6
    - 3.7
    - 3.8
cache: pip
addons:
    apt:
        update:
            - true
        packages:
            - qpdf
            - xpdf
            - libimage-exiftool-perl
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
install:
    - pip install -r requirements.txt -r requirements.dev.txt
script:
    - make test
