language: python
python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8
cache: pip
before_install:
    - python --version
    - pip install -U pip --user
    - pip install -U pytest --user
install:
    - pip install -r requirements.txt -r requirements.dev.txt --user
script:
    - make test
