language: python
os:
    - linux
python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8
cache: pip
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
install:
    - [ "$TRAVIS_OS_NAME" = "linux" ] && sudo apt install -y qpdf xpdf libimage-exiftool-perl
    - pip install -r requirements.txt -r requirements.dev.txt
script:
    - make test
