version: 2.1
orbs:
    python: circleci/python@0.2.1
jobs:
    build: &common-build
        docker:
            - image: circleci/python
        steps:
            - checkout
            - python/load-cache
            - run: sudo apt update
            - run: sudo apt install -y qpdf xpdf libimage-exiftool-perl poppler-utils
            - run: pip install --user -r requirements.txt -r requirements.dev.txt
            - python/save-cache
            - run: make test
            - run: bash <(curl -s https://codecov.io/bash)
            - store_test_results:
                path: test-results
            - store_artifacts:
                path: test-results
    build-python35:
        <<: *common-build
        docker:
            - image: circleci/python:3.5.9-stretch
    build-python36:
        <<: *common-build
        docker:
            - image: circleci/python:3.6.10-jessie
    build-python37:
        <<: *common-build
        docker:
            - image: circleci/python:3.7.7-stretch
    build-python38:
        <<: *common-build
        docker:
            - image: circleci/python:3.8.2-buster

workflows:
    version: 2
    build:
        jobs:
            - build-python35
            - build-python36
            - build-python37
            - build-python38
